config/routes.rb
GalleryApp::Application.routes.draw do
  root :to => "galleries#index"

  resources :galleries do
    resources :paintings
  end

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :address, :name, :paintings_attributes
  has_many :paintings, :dependent => :destroy
  accepts_nested_attributes_for :paintings, :reject_if => lambda { |painting| painting[:title].blank? }, :allow_destroy => true
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :artist, :description, :gallery_id, :image, :price, :title, :remote_image_url
  belongs_to :gallery
  mount_uploader :image, ImageUploader

private

  def self.reprocess_all!
    all.each do |painting|
      painting.image.recreate_versions!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  before_filter :fetch_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
    3.times { @gallery.paintings.build }
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  def create
    @gallery = Gallery.new(params[:gallery])
    if @gallery.save
      redirect_to @gallery, notice: 'Gallery was successfully created.'
    else
      render :new
    end
  end

  # PUT /galleries/1
  def update
    if @gallery.update_attributes(params[:gallery])
      redirect_to @gallery, notice: 'Gallery was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /galleries/1
  def destroy
    @gallery.destroy
    redirect_to galleries_url
  end

  private
  def fetch_gallery
    @gallery = Gallery.find(params[:id])
  end

end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

  before_filter :fetch_gallery
  before_filter :fetch_painting, only: [:show, :edit, :update, :destroy]

  # GET /gallery/99/paintings
  def index
    @paintings = @gallery.paintings
    redirect_to @gallery
  end

  # GET /gallery/99/paintings/1
  def show
  end

  # GET /gallery/99/paintings/new
  def new
    @painting = @gallery.paintings.build
  end

  # GET /gallery/99/paintings/1/edit
  def edit
  end

  # POST /gallery/99/paintings
  def create
    @painting = @gallery.paintings.build(params[:painting])
    if @painting.save
      redirect_to gallery_painting_path(@gallery, @painting), notice: 'Painting was successfully created.'
    else
      render :new
    end
  end

  # PUT /gallery/99/paintings/1
  def update
    if @painting.update_attributes(params[:painting])
      redirect_to gallery_painting_path(@gallery, @painting), notice: 'Painting was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gallery/99/paintings/1
  def destroy
    @painting.destroy
    redirect_to gallery_url(@gallery)
  end


  private
  def fetch_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end


  private
  def fetch_painting
    @painting = @gallery.paintings.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@gallery.errors.count, "error")} prohibited this gallery from being saved:" %>
      </h2>
      <ul>
        <% @gallery.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  Paintings:
  <br/>
  <br/>
  <%= f.fields_for :paintings do |sub_form| %>
    <fieldset>
      <div class="field">
        <%= sub_form.label :title %>
        <%= sub_form.text_field :title %>
      </div>
      <div class="field">
        <%= sub_form.label :artist %>
        <%= sub_form.text_field :artist %>
      </div>
      <div class="field">
        <%= sub_form.label :description %>
        <%= sub_form.text_field :description %>
      </div>
      <div class="field">
        <%= sub_form.label :price %>
        <%= sub_form.number_field :price %>
      </div>
      <div class="field">
        <%= sub_form.label :image %>
        <%= sub_form.file_field :image %>
      </div>
      <div class="field">
        <%= sub_form.label :remote_image_url, 'or add by URL' %>
        <%= sub_form.url_field :remote_image_url %>
      </div>
      <%= sub_form.check_box :_destroy %>
      <%= sub_form.label :_destroy, "Remove Painting" %>
    </fieldset>
    <br/>
  <% end %>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>
<%= render 'form' %>
<%= link_to 'Show', @gallery %>
|
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<h1>Galleries</h1>
<% @galleries.each do |gallery| %>
  <div class="gallery">
    <h2>
      <%= link_to gallery.name, gallery %>
    </h2>
    Paintings: <%=gallery.paintings.size %>
  </div>
<% end %>
<p>
  <%= link_to "New Gallery", new_gallery_path %>
</p>

app/views/galleries/new.html.erb
<h1>New gallery</h1>
<%= render 'form' %>
<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<h1>
  <%= @gallery.name %>
</h1>
<div id="paintings">
  <% for painting in @gallery.paintings %>
    <div class="painting">
      <%= link_to gallery_painting_path(@gallery, painting) do %>
        <%= image_tag painting.image_url(:thumb) %>
      <% end %>
      <div class="name">
        <%= link_to painting.title, gallery_painting_path(@gallery, painting) %>
      </div>
      <div class="actions">
        <%= link_to "edit", edit_gallery_painting_path(@gallery, painting) %>
        |
        <%= link_to "remove", gallery_painting_path(@gallery, painting), :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>
<p>
  <%= link_to "Add a Painting", new_gallery_painting_path(@gallery) %>
  |
  <%= link_to "Edit Gallery", edit_gallery_path(@gallery) %>
  |
  <%= link_to "Remove Gallery", @gallery, :confirm => 'Are you sure?', :method => :delete %>
  |
  <%= link_to "View Galleries", galleries_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>Gallery App</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/paintings/_form.html.erb
<%= form_for [@gallery, @painting] do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@painting.errors.count, "error")} prohibited this painting from being saved:" %>
      </h2>
      <ul>
        <% @painting.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <%= image_tag @painting.image_url(:thumb) if @painting.image? %>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url, 'or add by URL' %>
    <%= f.url_field :remote_image_url %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/paintings/edit.html.erb
<h1>Editing painting</h1>
<%= render 'form' %>
<%= link_to 'Show', gallery_painting_path(@painting.gallery, @painting) %>
|
<%= link_to 'Back', gallery_paintings_path(@painting.gallery) %>

app/views/paintings/new.html.erb
<h1>New painting</h1>
<%= render 'form' %>
<%= link_to "Back to Gallery", @painting.gallery %>

app/views/paintings/show.html.erb
<h1>
  <%= @painting.title %>
</h1>
<p>
  <b>Artist:</b>
  <%= @painting.artist %>
</p>
<p>
  <b>Description:</b>
  <%= @painting.description %>
</p>
<p>
  <b>Price:</b>
  <%= @painting.price %>
</p>
<p>
  <b>Gallery:</b>
  <%= @painting.gallery.name %>
</p>
<p>
  <%= image_tag @painting.image_url if @painting.image? %>
</p>
<%= link_to 'Edit', edit_gallery_painting_path(@painting.gallery, @painting) %>
|
<%= link_to "Back to Gallery", @painting.gallery %>